project:
  type: website

website:
  title: "CompareMap"
  navbar:
    left:
      - href: index.qmd
        text: Tutorial

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



